/// Generated by AssetsRefGenerator on 2021/08/03
class Res {
  static const String account = "assets/icons/account.svg";
  static const String setting = "assets/icons/setting.png";
  static const String user = "assets/icons/user.svg";
  static const String kst = "assets/images/kst.png";
  static const String sad_face = "assets/images/sad_face.png";
}
